### ISSUE TITLE
Not enough space for BNC locator pins

### ISSUE THREAD

**Issue by timgiles** [dangrie158/AdapterBox#3]
Every other part seemed to have the correct size hole(s) and spacing - but for me, the given BNC connector would not fit the two locator pins at the same time. I suspect therefore that your layout for the part is incorrect. To confirm, I ordered the exact BNC from Conrad.

**Comment by dangrie158** [comment]
Thanks for the feedback. This should be fixed by [a832ae4](https://github.com/dangrie158/AdapterBox/commit/a832ae4d49a8491ea860509758d1a86a95824ddd).
